name: "Deployment"
on:
  pull_request:
    types:
      - closed

defaults:
  run:
    shell: bash -l {0}

jobs:
  Automation:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Setup Arturo"
        uses: arturo-lang/arturo-action@main

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Update package info
        run: |
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          arturo tools/deploy.art
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: drkameleon
          author_email: yaniszaf@gmail.com
          message: 'CI Package Deployment'
          add: '*.art'

      - name: Update registry
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/pkgr.art
            git pull