name: "Packages"
on:
  push:
    branches:
      '!main'
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:  
  Verification:
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Setup Arturo"
        uses: arturo-lang/arturo-action@main

      - name: "Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: "Install gems"
        run: |
          gem install commonmarker

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Run unit tests
        run: |
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          arturo tools/ci.art
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}