name: "Packages"
on:
  push:
    branches:
      '!main'
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:  
  Verification:
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Setup Arturo"
        uses: arturo-lang/arturo-action@main

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Run unit tests
        run: |
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          arturo tools/ci.art
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            whoami
            ls -al